# Generated by Django 4.2.30 on 2026-07-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(max_length=20)),
                ('license_expiry', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('safety_score', models.FloatField(default=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended')], default='available', max_length=20)),
            ],
        ),
    ]
