# Generated by Django 4.2.30 on 2026-07-12 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_category',
            field=models.CharField(choices=[('LMV', 'Light Motor Vehicle'), ('HMV', 'Heavy Motor Vehicle'), ('HPMV', 'Heavy Passenger Motor Vehicle'), ('MGV', 'Medium Goods Vehicle')], max_length=20),
        ),
    ]
