# Generated by Django 4.2.30 on 2026-07-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_created_at_alter_driver_license_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, help_text='For license expiry reminders', max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='reminder_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
