# Generated by Django 4.2.30 on 2026-07-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='odometer_at_fill',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('toll', 'Toll'), ('maintenance', 'Maintenance'), ('parking', 'Parking'), ('fine', 'Fine'), ('other', 'Other')], max_length=20),
        ),
    ]
