# Generated by Django 4.2.30 on 2026-07-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('van', 'Van'), ('truck', 'Truck'), ('bike', 'Bike'), ('car', 'Car')], max_length=20)),
                ('max_load_capacity', models.FloatField(help_text='in kg')),
                ('odometer', models.FloatField(default=0)),
                ('acquisition_cost', models.FloatField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
