# Generated by Django 4.2.30 on 2026-07-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('rc_book', 'RC Book'), ('insurance', 'Insurance'), ('pollution', 'Pollution Certificate (PUC)'), ('fitness', 'Fitness Certificate'), ('permit', 'Route Permit'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='vehicle_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
        ),
    ]
