# Generated by Django 4.2.30 on 2026-07-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
